print('===EXERCÍCIO 026===')
cidade = str(input('Digite o nome da sua cidade: ')).title().strip()
lista = cidade.split()
print(f"Sua cidade começa com a palavra Santo?\033[36m{'Santo' in lista[0]}\033[m")
print(f'Sua cidade é a cidade de(o) \033[36m{cidade}\033[m')
cid = str(input('Digite a cidade em que você nasceu: ')).strip()  # .title()
print(f'\033[36m{cid}\033[m possui "Santo" no nome?')
print(cid[:5].upper() == 'SANTO')
print(f'A cidade que você nasceu é a cidade de \033[36m{cid}\033[m')
